#!/bin/bash

make -j2 clean
make -j2 distclean
for i in `find . -type f -name "*.orig"`; do rm $i; done
for i in `find . -type f -name "*.rej"`; do rm $i; done
for i in `find . -type f -name "*.bak"`; do rm $i; done
